[GENERAL]
xpath_file_path = None
page_folder_path =
workflow_doc_path =
feature_file_path =
git_file_path = Page_files
git_repo_name =
git_branch_name =

[Source]
source_type = local
# Options: local, git
