[GENERAL]
xpath_file_path = None
page_folder_path = D:\Self_healing_web_application\source_folder\Pages
workflow_doc_path = C:\Users\sathanantham.aru\PycharmProjects\ai-accelerator\output\Action_collection\Sep_sauce_complete_actions.txt
feature_file_path=D:\Self_healing_web_application\sauce_demo.feature
page_folder_path_new = D:\Self_healing_web_application\source_folder\Pages
xpath_file_path_new = D:\Self_healing_web_application\source_folder\OR\saucedemoobjectrepository.py
git_file_path = Page_files
git_repo_name= https://git.tigeranalytics.com/tiger-internal/qe/qe_solutions
git_branch_name=Self_healing_demo

[Source]
source_type = git
# Options: local, git
