"""
step1_extract — Flow 1 (KPI) extraction

Auto-generated by PBI Validator. Runs headless — no Streamlit, no LLM.
Usage:  python step1_extract  [inputs.xlsx]
"""
import sys, os, json
import pandas as pd
sys.path.insert(0, r"C:\Users\sathanantham.aru\PycharmProjects\ai-accelerator\pbi_validator")
from utils import pipeline

_DEFAULT_INPUTS = "extract_inputs.xlsx"

def _cfg_path():
    return sys.argv[1] if len(sys.argv) > 1 else _DEFAULT_INPUTS

def login(driver, url):
    """TODO — implement your Power BI authentication here.

    The browser is already open at `url`. Log in and navigate to the report page
    you want to validate, then simply return. This is intentionally a stub.
    """
    import time
    print("[login] STUB — implement login(). Pausing 30s for manual login...")
    time.sleep(30)

def main():
    cfg     = pipeline.read_config_xlsx(_cfg_path())
    url     = cfg["url"]
    mode    = cfg.get("extraction_mode") or "table"     # 'table' or 'screenshot'
    out_dir = cfg.get("output_dir") or "."
    os.makedirs(out_dir, exist_ok=True)

    print("Opening report and extracting KPIs...")
    driver = pipeline.open_report(url, login)
    try:
        kpis, tables, slicers = pipeline.extract_flow1(driver, pipeline.make_llm(), mode)
    finally:
        try: driver.quit()
        except Exception: pass

    pd.DataFrame(kpis).to_csv(os.path.join(out_dir, "kpi_extraction.csv"), index=False)
    with open(os.path.join(out_dir, "visuals.json"), "w", encoding="utf-8") as fh:
        json.dump({"table_results": tables, "slicers": slicers}, fh, default=str, indent=2)
    print(f"Extracted {len(kpis)} KPIs -> {out_dir} (kpi_extraction.csv + visuals.json)")

if __name__ == "__main__":
    main()
