"""
Generate standalone, runnable scripts that replay each stage of the PBI Validator
headlessly — no Streamlit, no LLM at runtime.

Chain (per flow the user ran):
    step1_extract.py   URL + (Flow 2: test-case combinations) -> extracted data
    step2_queries.py   the user's REVIEWED queries, embedded verbatim (direct copy)
    step3_validate.py  reviewed queries + DB creds -> validation report

All parameters are supplied via an Excel workbook (Config sheet [+ Combinations
sheet for Flow 2 test cases]). Scripts import the shared ``utils.pipeline`` so the
logic never diverges from the app.
"""

import json
import os

# Absolute path to the `pbi_validator` package dir — baked into scripts so they
# can `from utils import pipeline` regardless of where they are run from.
_PKG_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

_LOGIN_STUB = '''\
def login(driver, url):
    """TODO — implement your Power BI authentication here.

    The browser is already open at `url`. Log in and navigate to the report page
    you want to validate, then simply return. This is intentionally a stub.
    """
    import time
    print("[login] STUB — implement login(). Pausing 30s for manual login...")
    time.sleep(30)
'''


def _header(title, default_inputs):
    return (
        '"""\n' + title + "\n\n"
        "Auto-generated by PBI Validator. Runs headless — no Streamlit, no LLM.\n"
        "Usage:  python " + title.split()[0].lower() + "  [inputs.xlsx]\n"
        '"""\n'
        "import sys, os, json\n"
        "import pandas as pd\n"
        f"sys.path.insert(0, r\"{_PKG_DIR}\")\n"
        "from utils import pipeline\n\n"
        f"_DEFAULT_INPUTS = \"{default_inputs}\"\n\n"
        "def _cfg_path():\n"
        "    return sys.argv[1] if len(sys.argv) > 1 else _DEFAULT_INPUTS\n\n"
    )


# ── STEP 1 — extraction ───────────────────────────────────────────────────────
def build_extract_script(flow: str) -> str:
    if flow == "slicer":
        body = '''
def main():
    cfg    = pipeline.read_config_xlsx(_cfg_path())
    combos = pipeline.read_combinations_xlsx(_cfg_path())   # each row = one test case
    url     = cfg["url"]
    out_dir = cfg.get("output_dir") or "."
    os.makedirs(out_dir, exist_ok=True)

    print(f"Opening report and running {len(combos)} test case(s) + 1 default...")
    driver = pipeline.open_report(url, login)
    try:
        def prog(i, n, label): print(f"  [{i+1}/{n}] {label}")
        sweep = pipeline.run_sweep(driver, combos, progress=prog)
    finally:
        try: driver.quit()
        except Exception: pass

    with open(os.path.join(out_dir, "sweep_data.json"), "w", encoding="utf-8") as fh:
        json.dump(sweep, fh, default=str, indent=2)
    print(f"Saved {len(sweep)} test case(s) -> {os.path.join(out_dir, 'sweep_data.json')}")

if __name__ == "__main__":
    main()
'''
        return (_header("step1_extract — Flow 2 (slicer) extraction",
                        "extract_inputs.xlsx")
                + _LOGIN_STUB + body)

    body = '''
def main():
    cfg     = pipeline.read_config_xlsx(_cfg_path())
    url     = cfg["url"]
    mode    = cfg.get("extraction_mode") or "table"     # 'table' or 'screenshot'
    out_dir = cfg.get("output_dir") or "."
    os.makedirs(out_dir, exist_ok=True)

    print("Opening report and extracting KPIs...")
    driver = pipeline.open_report(url, login)
    try:
        kpis, tables, slicers = pipeline.extract_flow1(driver, pipeline.make_llm(), mode)
    finally:
        try: driver.quit()
        except Exception: pass

    pd.DataFrame(kpis).to_csv(os.path.join(out_dir, "kpi_extraction.csv"), index=False)
    with open(os.path.join(out_dir, "visuals.json"), "w", encoding="utf-8") as fh:
        json.dump({"table_results": tables, "slicers": slicers}, fh, default=str, indent=2)
    print(f"Extracted {len(kpis)} KPIs -> {out_dir} (kpi_extraction.csv + visuals.json)")

if __name__ == "__main__":
    main()
'''
    return (_header("step1_extract — Flow 1 (KPI) extraction", "extract_inputs.xlsx")
            + _LOGIN_STUB + body)


# ── STEP 2 — reviewed queries (direct copy, no LLM) ─────────────────────────────
def build_queries_script(flow: str, queries: list, col_map: dict = None) -> str:
    q_json = json.dumps(queries or [], indent=2)
    head = (
        '"""\n'
        "step2_queries — the queries you REVIEWED in the app, embedded verbatim.\n"
        "No LLM, no generation: this is a direct, deterministic copy. Edit here if\n"
        "you need to tweak a query; step3_validate imports these.\n"
        '"""\n'
        "import json\n\n"
    )
    if flow == "slicer":
        return (head
                + "BASE_QUERIES = json.loads(r'''\n" + q_json + "\n''')\n\n"
                + "SLICER_COL_MAP = json.loads(r'''\n"
                + json.dumps(col_map or {}, indent=2) + "\n''')\n")
    return (head + "REFERENCE_QUERIES = json.loads(r'''\n" + q_json + "\n''')\n")


# ── STEP 3 — validation ─────────────────────────────────────────────────────────
def build_validate_script(flow: str) -> str:
    if flow == "slicer":
        body = '''
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from step2_queries import BASE_QUERIES, SLICER_COL_MAP

def main():
    cfg     = pipeline.read_config_xlsx(_cfg_path())
    in_dir  = cfg.get("input_dir") or "."
    out_dir = cfg.get("output_dir") or "."
    os.makedirs(out_dir, exist_ok=True)

    with open(os.path.join(in_dir, "sweep_data.json"), encoding="utf-8") as fh:
        sweep = json.load(fh)

    conn = pipeline.connection_from_config(cfg)
    def prog(i, n, label): print(f"  [{i+1}/{n}] {label}")
    results = pipeline.validate_combinations(
        conn, sweep, BASE_QUERIES, SLICER_COL_MAP,
        float(cfg.get("tolerance", 0.1) or 0.1), None,
        db_type=cfg.get("db_type"), catalog=cfg.get("catalog", ""),
        schema=cfg.get("schema", ""), progress=prog,
    )
    df = pd.DataFrame(results)
    out = os.path.join(out_dir, "pbi_combination_validation.xlsx")
    df.to_excel(out, index=False)
    _summary(df, out)

def _summary(df, out):
    if df.empty:
        print("No results."); return
    counts = df["Status"].value_counts().to_dict() if "Status" in df else df["status"].value_counts().to_dict()
    print(f"Done -> {out}  |  {counts}")

if __name__ == "__main__":
    main()
'''
        return (_header("step3_validate — Flow 2 (slicer) validation",
                        "validate_inputs.xlsx") + body)

    body = '''
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from step2_queries import REFERENCE_QUERIES

def main():
    cfg     = pipeline.read_config_xlsx(_cfg_path())
    in_dir  = cfg.get("input_dir") or "."
    out_dir = cfg.get("output_dir") or "."
    os.makedirs(out_dir, exist_ok=True)

    kpis = pd.read_csv(os.path.join(in_dir, "kpi_extraction.csv")).to_dict("records")
    conn = pipeline.connection_from_config(cfg)
    results = pipeline.validate_kpi_list(
        conn, kpis, REFERENCE_QUERIES,
        float(cfg.get("tolerance", 0.1) or 0.1), None,
        db_type=cfg.get("db_type"), catalog=cfg.get("catalog", ""),
        schema=cfg.get("schema", ""),
    )
    df = pd.DataFrame(results)
    out = os.path.join(out_dir, "pbi_validation_report.xlsx")
    df.to_excel(out, index=False)
    counts = df["status"].value_counts().to_dict() if not df.empty else {}
    print(f"Done -> {out}  |  {counts}")

if __name__ == "__main__":
    main()
'''
    return (_header("step3_validate — Flow 1 (KPI) validation", "validate_inputs.xlsx")
            + body)


# ── Pre-filled input workbooks ──────────────────────────────────────────────────
def extract_inputs(flow, url="", combos=None):
    """(config_dict, combinations|None) prefilled for the extract step."""
    from utils import pipeline
    if flow == "slicer":
        cfg = {"url": url, "output_dir": "output"}
        return cfg, (combos or [])
    cfg = {"url": url, "extraction_mode": "table", "output_dir": "output"}
    return cfg, None


def validate_inputs(db=None):
    """Config dict prefilled for the validate step from a db-settings dict."""
    db = db or {}
    return {
        "db_type":   db.get("db_type", "databricks"),
        "host":      db.get("host", ""),
        "port":      db.get("port", ""),
        "database":  db.get("database", ""),
        "user":      db.get("user", ""),
        "password":  db.get("password", ""),
        "http_path": db.get("http_path", ""),
        "catalog":   db.get("catalog", ""),
        "schema":    db.get("schema", ""),
        "tolerance": db.get("tolerance", 0.1),
        "input_dir":  "output",
        "output_dir": "output",
    }
